let equipTable;
let typeTable;
createTables();

//Переход к нопке добавить ряд-----------------------------------------------------
//кнопка "добавить ряд" (выводит форму для нового ряда)
document.getElementById("add-row-button").addEventListener("click",function (){
    let equipForm = document.querySelector("#main-form");
    equipForm.style.display = "block";
    let main = document.querySelector("main");
    main.style.opacity = "0.5";
    main.style.filter = "blur(5px)";
    document.body.style.overflow = "hidden"; //Убрали возможность скролить после нажатия
    document.getElementById("overlay").style.display = "block";

    //Загружаем типы в форму из таблицы typeTable (но сначала очищаем, чтобы не дублировались):
    let typeSelect = document.querySelector("#type-select");
    while (typeSelect.firstChild) {
        typeSelect.removeChild(typeSelect.firstChild);
    }
    let freshOption = document.createElement("option");
    freshOption.selected = true;
    freshOption.hidden = true;
    freshOption.value = "default";
    freshOption.text = "Выберите тип";
    typeSelect.appendChild(freshOption);
    let typesArray = typeTable.getData();
    for (let row of typesArray){
        let freshOption = document.createElement("option");
        freshOption.value = row['type'];
        freshOption.text = row['type'];
        typeSelect.appendChild(freshOption);
    }
})
//Крестик (закрыть форму)
document.getElementById("form-exit").addEventListener("click",function (){
    let equipForm = document.querySelector("#main-form");
    equipForm.style.display = "none";
    let main = document.querySelector("main");
    main.style.opacity = "1";
    main.style.filter = "blur(0px)";
    document.body.style.overflow = "visible"; //Вернули возможность скролить после нажатия
    document.getElementById("overlay").style.display = "none";
    let typeSelect = document.querySelector("#type-select");
})
//-----------------------------------------------------------------------------------

//переход к кнопке "редактировать типы"--------------------------------
document.getElementById("set-equip-types-button").addEventListener("click",function (){
    let typeTable = document.querySelector("#type-table");
    typeTable.style.visibility = "visible";
    typeTable.style.opacity = "1";
    let typeTableDiv = document.querySelector("#type-table-box");
    typeTableDiv.style.opacity = "1";
    typeTableDiv.style.visibility = "visible";
    let main = document.querySelector("main");
    main.style.opacity = "0.5";
    main.style.filter = "blur(5px)";
    document.body.style.overflow = "hidden"; //Убрали возможность скролить после нажатия
    document.getElementById("overlay").style.display = "block";
})

//При нажатии на кнопку "добавить тип"
document.getElementById("add-type-button").addEventListener("click",function (){
    typeTable.addRow({});
})
//Предыдущая стр. типов
document.getElementById("prev-page-type").addEventListener("click",function (){
    typeTable.previousPage();
})
//Следующая стр. типов
document.getElementById("next-page-type").addEventListener("click",function (){
    typeTable.nextPage();
})
//Крестик (закрыть типы)
document.getElementById("type-exit").addEventListener("click",function (){
    let typeTable = document.querySelector("#type-table");
    typeTable.style.visibility = "hidden";
    typeTable.style.opacity = "0";
    let typeTableDiv = document.querySelector("#type-table-box");
    typeTableDiv.style.opacity = "0";
    typeTableDiv.style.visibility = "hidden";
    let main = document.querySelector("main");
    main.style.opacity = "1";
    main.style.filter = "blur(0px)";
    document.body.style.overflow = "visible"; //Вернули возможность скролить после нажатия
    document.getElementById("overlay").style.display = "none";
})

//---------------------------------------------------------------------

function createTables(){
    let tableData = [
        {
            "id":13806,
            "naming":"Hyper Tough Hyper Tough 12-in-1 Hammer Multitool, Black, Model 42865",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":6,
            "price4each":6,
            "totalLeft":6,
            "amountLeft":1,
            "unit":"шт.",
            "givenAmount":1,
            "givenTotal":6,
            "link":"https:\/\/www.walmart.com\/ip\/Hyper-Tough-12-in-1-Hammer-Multitool-Black-Model-42865\/379058402?from=\/search",
            "source":"Walmart",
            "supplyDate":"13.02.2024"
        },
        {
            "id":13805,
            "naming":"Hyper Tough Hyper Tough 1.5 Amp Corded Rotary Tool, Variable Speed with 105 Rotary Accessories & Storage Case, 120 Volts",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":22.97,
            "price4each":22.97,
            "totalLeft":22.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Hyper-Tough-1-5-Amp-Corded-Rotary-Tool-Variable-Speed-with-105-Rotary-Accessories-Storage-Case-120-Volts\/388836290?athbdg=L1200&from=\/search",
            "source":"Walmart",
            "supplyDate":"13.02.2024"
        },
        {
            "id":13804,
            "naming":"Super Sliders Super Sliders 1\" Round Rubber Tip Chair Leg Caps Floor Protection Pad White, 4 Pack",
            "type":"For hair",
            "responsible":"And Adam",
            "amount":4,
            "total":3.44,
            "price4each":0.86,
            "totalLeft":3.44,
            "amountLeft":4,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Super-Sliders-1-Round-Rubber-Tip-Chair-Leg-Caps-Floor-Protection-Pad-White-4-Pack\/16782106?from=\/search",
            "source":"Walmart",
            "supplyDate":"13.02.2024"
        },
        {
            "id":13803,
            "naming":"DIABLO 4-1\/2 in. x 24-Tooth Framing Circular Saw Blade",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":15.77,
            "price4each":15.77,
            "totalLeft":15.77,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/DIABLO-4-1-2-in-x-24-Tooth-Framing-Circular-Saw-Blade-D0424X\/309508784",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13802,
            "naming":"DIABLO Steel Demon 4-1\/2 in. x 0.045 in. x 7\/8 in. Metal Cut Off Type 1",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":4.47,
            "price4each":4.47,
            "totalLeft":4.47,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/DIABLO-Steel-Demon-4-1-2-in-x-0-045-in-x-7-8-in-Metal-Cut-Off-Type-1-DBDS45045101F\/310832755",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13801,
            "naming":"DIABLO 4-1\/2 in. x 1\/4 in. x 7\/8 in. Masonry Grinding Disc with Type 27 Depressed Center",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":3.97,
            "price4each":3.97,
            "totalLeft":3.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/DIABLO-4-1-2-in-x-1-4-in-x-7-8-in-Masonry-Grinding-Disc-with-Type-27-Depressed-Center-DBD045250701C\/202831032",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13800,
            "naming":"3M 0.94 in. x 60.1 Yds. Multi-Surface Contractor Grade Tan Masking Tape (1 Roll)",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":2.48,
            "price4each":2.48,
            "totalLeft":2.48,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/3M-0-94-in-x-60-1-Yds-Multi-Surface-Contractor-Grade-Tan-Masking-Tape-1-Roll-2020-24AP\/100207133",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13799,
            "naming":"Charlotte Pipe 3\/4 in. PVC Schedule. 40 90° S x S Elbow Fitting",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":0.79,
            "price4each":0.79,
            "totalLeft":0.79,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Charlotte-Pipe-3-4-in-PVC-Schedule-40-90-S-x-S-Elbow-Fitting-PVC023000800HD\/203812123",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13798,
            "naming":"Carlon 3\/4 in. 90-Degree Schedule 40 Standard Radius Belled End Elbow",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":1.31,
            "price4each":1.31,
            "totalLeft":1.31,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Carlon-3-4-in-90-Degree-Schedule-40-Standard-Radius-Belled-End-Elbow-UA9AEB-CTN\/202304074",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13797,
            "naming":"RYOBI ONE+ 18V Cordless 4-1\/2 in. Angle Grinder (Tool Only)",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":59.97,
            "price4each":59.97,
            "totalLeft":59.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/RYOBI-ONE-18V-Cordless-4-1-2-in-Angle-Grinder-Tool-Only-PCL445B\/318696913",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13786,
            "naming":"Husky 12 ft. Tape Measure",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":5.97,
            "price4each":5.97,
            "totalLeft":5.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-16-ft-Tape-Measure-90647\/320510417",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13785,
            "naming":"Commercial Electric 3\/4 in. Electrical Metallic Tubing (EMT) Set-Screw Coupling (25-Pack)",
            "type":"For hair",
            "responsible":"G R",
            "amount":5,
            "total":2.84,
            "price4each":0.57,
            "totalLeft":2.84,
            "amountLeft":5,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Commercial-Electric-3-4-in-Electrical-Metallic-Tubing-EMT-Set-Screw-Coupling-25-Pack-FEPSS-75-25\/316098066",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13784,
            "naming":"Halex (Brand Rating: 4.5\/5) 3\/4 in. Electrical Metallic Tube (EMT) Pull Elbow",
            "type":"For hair",
            "responsible":"G R",
            "amount":2,
            "total":9.12,
            "price4each":4.56,
            "totalLeft":9.12,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Halex-3-4-in-Electrical-Metallic-Tube-EMT-Pull-Elbow-14407\/100111131",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13783,
            "naming":"Milwaukee INKZALL Blue Fine Point Jobsite Permanent Marker",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":0.98,
            "price4each":0.98,
            "totalLeft":0.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Milwaukee-INKZALL-Blue-Fine-Point-Jobsite-Permanent-Marker-48-22-3180\/205984569",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13782,
            "naming":"Empire 36 in. Aluminum Straight Edge Ruler",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":6.97,
            "price4each":6.97,
            "totalLeft":6.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Empire-36-in-Aluminum-Straight-Edge-Ruler-403\/100185157",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13781,
            "naming":"Anvil 18 mm and 9 mm Snap-Off Knife Set (2-Piece)",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":2,
            "total":2.97,
            "price4each":1.49,
            "totalLeft":2.97,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Anvil-18-mm-and-9-mm-Snap-Off-Knife-Set-2-Piece-86-212-0111\/303711777",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13780,
            "naming":"30 in. W x 36 in. H Rectangular Frameless Beveled Edge Wall Bathroom Vanity Mirror in Silver",
            "type":"For hair",
            "responsible":"G R",
            "amount":2,
            "total":15.2,
            "price4each":7.6,
            "totalLeft":15.2,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Glacier-Bay-30-in-W-x-36-in-H-Rectangular-Frameless-Beveled-Edge-Wall-Bathroom-Vanity-Mirror-in-Silver-81176\/316331996",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13779,
            "naming":"FOAMULAR 1\/2 in. x 4 ft. x 8 ft. R-3 Square Edge Rigid Foam Board Insulation Sheathing",
            "type":"For hair",
            "responsible":"G R",
            "amount":2,
            "total":41,
            "price4each":20.5,
            "totalLeft":41,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Owens-Corning-FOAMULAR-1-2-in-x-4-ft-x-8-ft-R-3-Square-Edge-Rigid-Foam-Board-Insulation-Sheathing-36L\/100320356",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13778,
            "naming":"3\/16 in. x 1-1\/4 in. Zinc-Plated Fender Washer",
            "type":"Consumables",
            "responsible":"G R",
            "amount":30,
            "total":5.4,
            "price4each":0.18,
            "totalLeft":5.4,
            "amountLeft":30,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Everbilt-3-16-in-x-1-1-4-in-Zinc-Plated-Fender-Washer-100-Pack-804780\/204276326",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13777,
            "naming":"LSTA 1-1\/4 in. x 9 in. 20-Gauge Galvanized Strap Tie",
            "type":"Consumables",
            "responsible":"G R",
            "amount":4,
            "total":3.52,
            "price4each":0.88,
            "totalLeft":3.52,
            "amountLeft":4,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Simpson-Strong-Tie-LSTA-1-1-4-in-x-9-in-20-Gauge-Galvanized-Strap-Tie-LSTA9\/202255804",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13776,
            "naming":"7 in. Polycast Rafter Square",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":5.47,
            "price4each":5.47,
            "totalLeft":5.47,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Empire-7-in-Polycast-Rafter-Square-296\/100154430",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13775,
            "naming":"3\/4 in. x 10 ft. Electric Metallic Tube (EMT) Conduit",
            "type":"For hair",
            "responsible":"G R",
            "amount":2,
            "total":19.96,
            "price4each":9.98,
            "totalLeft":19.96,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/3-4-in-x-10-ft-Electric-Metallic-Tube-EMT-Conduit-853429\/100400406",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13774,
            "naming":"1 in. x 3 in. x 8 ft. Furring Strip Board",
            "type":"For hair",
            "responsible":"G R",
            "amount":7,
            "total":13,
            "price4each":1.86,
            "totalLeft":13,
            "amountLeft":7,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/1-in-x-3-in-x-8-ft-Furring-Strip-Board-164704\/100094214",
            "source":"The Home Depot",
            "supplyDate":"12.02.2024"
        },
        {
            "id":13733,
            "naming":"Parent Grip White Door Knob Covers (4-Pack)",
            "type":"Home equipment",
            "responsible":"And Adam",
            "amount":4,
            "total":4.48,
            "price4each":1.12,
            "totalLeft":2.24,
            "amountLeft":2,
            "unit":"шт.",
            "givenAmount":-2,
            "givenTotal":-2.24,
            "link":"https:\/\/www.homedepot.com\/p\/Safety-1st-Parent-Grip-White-Door-Knob-Covers-4-Pack-HS326\/309495997",
            "source":"The Home Depot",
            "supplyDate":"10.02.2024"
        },
        {
            "id":13732,
            "naming":"Brandywine Stainless Steel Hall\/Closet Door Knob",
            "type":"Home equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":8,
            "price4each":8,
            "totalLeft":0,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Defiant-Brandywine-Stainless-Steel-Hall-Closet-Door-Knob-32T8630B\/323700939",
            "source":"The Home Depot",
            "supplyDate":"10.02.2024"
        },
        {
            "id":13730,
            "naming":"WD-40 Multi-Use Product with Smart Straw Sprays 2 Ways, 8 OZ [6-Pack]",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":6,
            "total":29.12,
            "price4each":4.85,
            "totalLeft":24.27,
            "amountLeft":5,
            "unit":"шт.",
            "givenAmount":1,
            "givenTotal":4.85,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B01ECA64U8\/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1",
            "source":"Amazon",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13729,
            "naming":"Clorox No-Splash Regular Liquid Bleach",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":117,
            "total":7.52,
            "price4each":0.06,
            "totalLeft":7.52,
            "amountLeft":117,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/clorox-no-splash-regular-liquid-bleach-117-oz\/3569028",
            "source":"HEB",
            "supplyDate":"31.01.2024"
        },
        {
            "id":13728,
            "naming":"Febreze Fabric Refresher Spray - Downy April Fresh Scent",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":1,
            "total":5.48,
            "price4each":5.48,
            "totalLeft":5.48,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/febreze-fabric-refresher-spray-downy-april-fresh-nbsp-scent-23-6-oz\/1807764",
            "source":"HEB",
            "supplyDate":"31.01.2024"
        },
        {
            "id":13727,
            "naming":"H‑E‑B Tru Grit Toilet Bowl Cleaner with Bleach",
            "type":"For toilet",
            "responsible":"G R",
            "amount":2,
            "total":3.96,
            "price4each":1.98,
            "totalLeft":3.96,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/h-e-b-tru-grit-toilet-bowl-cleaner-with-bleach-24-oz\/2161615",
            "source":"HEB",
            "supplyDate":"31.01.2024"
        },
        {
            "id":13726,
            "naming":"Lysol Power Clinging Gel Toilet Bowl Cleaner Value Pack",
            "type":"For toilet",
            "responsible":"G R",
            "amount":2,
            "total":4.97,
            "price4each":2.48,
            "totalLeft":4.97,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/lysol-power-clinging-gel-toilet-bowl-cleaner-value-pack-48-oz\/1358484",
            "source":"HEB",
            "supplyDate":"31.01.2024"
        },
        {
            "id":13725,
            "naming":"Scrub Daddy Scratch Free Cleaning Tool",
            "type":"Consumables",
            "responsible":"G R",
            "amount":1,
            "total":3.98,
            "price4each":3.98,
            "totalLeft":3.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/scrub-daddy-scratch-free-cleaning-tool-each\/1924930",
            "source":"HEB",
            "supplyDate":"31.01.2024"
        },
        {
            "id":13724,
            "naming":"Comet Scratch Free Powder Cleanser with Bleach",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":5,
            "total":5.4,
            "price4each":1.08,
            "totalLeft":5.4,
            "amountLeft":5,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/comet-scratch-free-powder-cleanser-with-bleach-21-oz\/612095",
            "source":"HEB",
            "supplyDate":"31.01.2024"
        },
        {
            "id":13706,
            "naming":"LSTA 1-1\/4 in. x 24 in. 20-Gauge Galvanized Strap Tie",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":6,
            "total":14.28,
            "price4each":2.38,
            "totalLeft":2.38,
            "amountLeft":1,
            "unit":"шт.",
            "givenAmount":5,
            "givenTotal":11.9,
            "link":"https:\/\/www.homedepot.com\/p\/Simpson-Strong-Tie-LSTA-1-1-4-in-x-24-in-20-Gauge-Galvanized-Strap-Tie-LSTA24\/100375306",
            "source":"The Home Depot",
            "supplyDate":"19.10.2023"
        },
        {
            "id":13669,
            "naming":"Home Defense Max Insect Killer Ready-to-Use Spray",
            "type":"For the lawn",
            "responsible":"And Adam",
            "amount":1,
            "total":5.97,
            "price4each":5.97,
            "totalLeft":5.97,
            "unit":"шт.",
            "givenAmount":1,
            "givenTotal":5.97,
            "link":"https:\/\/www.homedepot.com\/p\/Ortho-24-oz-Home-Defense-Max-Insect-Killer-Ready-to-Use-Spray-0195610\/203687638",
            "source":"The Home Depot",
            "supplyDate":"04.02.2024"
        },
        {
            "id":13668,
            "naming":"32 oz. 3,500 sq. ft. All Season Ready-to-Spray Concentrate Lawn Fertilizer",
            "type":"For the lawn",
            "responsible":"And Adam",
            "amount":32,
            "total":10.47,
            "price4each":0.33,
            "totalLeft":10.47,
            "amountLeft":32,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Vigoro-32-oz-3-500-sq-ft-All-Season-Ready-to-Spray-Concentrate-Lawn-Fertilizer-Hg-52512-3\/204706227",
            "source":"The Home Depot",
            "supplyDate":"04.02.2024"
        },
        {
            "id":13667,
            "naming":"Smart Seed Texas Bermudagrass 1.75 lb. 1,000 sq. ft. Grass Seed and Lawn Fertilizer",
            "type":"For the lawn",
            "responsible":"And Adam",
            "amount":1,
            "total":14.97,
            "price4each":14.97,
            "totalLeft":0,
            "unit":"шт.",
            "givenTotal":14.97,
            "link":"https:\/\/www.homedepot.com\/p\/Pennington-Smart-Seed-Texas-Bermudagrass-1-75-lb-1-000-sq-ft-Grass-Seed-and-Lawn-Fertilizer-100543736\/314933305",
            "source":"The Home Depot",
            "supplyDate":"04.02.2024"
        },
        {
            "id":13664,
            "naming":"10 lbs. Picture Hanger Value Pack (50-Pack)",
            "type":"For hair",
            "responsible":"And Adam",
            "amount":50,
            "total":8.93,
            "price4each":0.18,
            "totalLeft":-0.07,
            "unit":"шт.",
            "givenAmount":50,
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/OOK-30-lbs-Picture-Hanger-Value-Pack-40-Pack-534281\/301942179",
            "source":"The Home Depot",
            "supplyDate":"02.02.2024"
        },
        {
            "id":13663,
            "naming":"Zinc Plated Steel Round Bend Screw Hooks (15-Pack)",
            "type":"For hair",
            "responsible":"And Adam",
            "amount":15,
            "total":7.68,
            "price4each":0.02,
            "totalLeft":7.56,
            "amountLeft":9,
            "unit":"шт.",
            "givenAmount":6,
            "givenTotal":-0.12,
            "link":"https:\/\/www.homedepot.com\/p\/Prime-Line-5-16-in-x-4-1-2-in-Zinc-Plated-Steel-Round-Bend-Screw-Hooks-10-Pack-9068625\/311949895",
            "source":"The Home Depot",
            "supplyDate":"02.02.2024"
        },
        {
            "id":13662,
            "naming":"Wooden Rod 48 in. x 0.75 in. Sanded Hardwood Ready for Finishing",
            "type":"For hair",
            "responsible":"And Adam",
            "amount":3,
            "total":11.01,
            "price4each":3.67,
            "totalLeft":0,
            "unit":"шт.",
            "givenAmount":3,
            "givenTotal":11.01,
            "link":"https:\/\/www.homedepot.com\/p\/Everbilt-Multi-Color-Push-Pin-Assortment-120-Pack-810742\/204769015",
            "source":"The Home Depot",
            "supplyDate":"02.02.2024"
        },
        {
            "id":13661,
            "naming":"Multi-Color Push Pin Assortment (120-Pack)",
            "type":"For hair",
            "responsible":"And Adam",
            "amount":120,
            "total":2.73,
            "price4each":0.02,
            "totalLeft":2.73,
            "amountLeft":120,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Everbilt-Multi-Color-Push-Pin-Assortment-120-Pack-810742\/204769015",
            "source":"The Home Depot",
            "supplyDate":"02.02.2024"
        },
        {
            "id":13660,
            "naming":"#18 x 5\/8 in. Zinc-Plated Wire Nails",
            "type":"For hair",
            "responsible":"And Adam",
            "amount":50,
            "total":2.18,
            "price4each":0.04,
            "totalLeft":2.18,
            "amountLeft":50,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/18-x-5-8-in-Zinc-Plated-Wire-Nails-801194\/204274053",
            "source":"The Home Depot",
            "supplyDate":"02.02.2024"
        },
        {
            "id":13654,
            "naming":"Spring Clamp Set (22-Piece) Anvil",
            "type":"For hair",
            "responsible":"G R",
            "amount":23,
            "total":9.97,
            "price4each":0.43,
            "totalLeft":9.97,
            "amountLeft":23,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Anvil-Spring-Clamp-Set-22-Piece-TGS0199A\/302755768",
            "source":"The Home Depot",
            "supplyDate":"01.02.2024"
        },
        {
            "id":13437,
            "naming":"Vertical Louver (8 Pack) 3.5 in W x 84 in. L (Actual Size 3.5 in W x 82.5 in. L )",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":8,
            "total":22.48,
            "price4each":2.81,
            "totalLeft":22.48,
            "amountLeft":8,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-Folding-Lock-Back-Utility-Knife-Red-with-10-Blades-99979\/311920676",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13436,
            "naming":"Folding Lock-Back Utility Knife, Red with 10-Blades",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":8.97,
            "price4each":8,
            "totalLeft":8,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-Folding-Lock-Back-Utility-Knife-Red-with-10-Blades-99979\/311920676",
            "source":"The Home Depot",
            "supplyDate":"30.01.2024"
        },
        {
            "id":13435,
            "naming":"24 in. 13-Pocket Black Canvas Tool Work Apron",
            "type":"Workwear",
            "responsible":"And Adam",
            "amount":1,
            "total":11.98,
            "price4each":11.98,
            "totalLeft":11.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-24-in-13-Pocket-Black-Canvas-Tool-Work-Apron-HD00121-TH\/310338131",
            "source":"The Home Depot",
            "supplyDate":"30.01.2024"
        },
        {
            "id":13434,
            "naming":"Ferris Single Hole Single-Handle Bathroom Faucet in Spot Defense Brushed Nickel",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":44,
            "price4each":44,
            "totalLeft":44,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "source":"The Home Depot",
            "supplyDate":"30.01.2024"
        },
        {
            "id":13433,
            "naming":"3\/8 in. Compression x 1\/2 in. FIP x 16 in. Braided Polymer Faucet Supply Line",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":2,
            "total":13.94,
            "price4each":6.97,
            "totalLeft":13.94,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/BrassCraft-3-8-in-Compression-x-1-2-in-FIP-x-16-in-Braided-Polymer-Faucet-Supply-Line-B1-16A-F\/100056596",
            "source":"The Home Depot",
            "supplyDate":"30.01.2024"
        },
        {
            "id":13431,
            "naming":"Tire gauge sli 20036",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":6.29,
            "price4each":6.29,
            "totalLeft":6.29,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "source":"OReilly",
            "supplyDate":"30.01.2024"
        },
        {
            "id":13430,
            "naming":"Silicone ver 78009",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":7.99,
            "price4each":7.99,
            "totalLeft":7.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "source":"OReilly",
            "supplyDate":"30.01.2024"
        },
        {
            "id":13429,
            "naming":"1\/2 in. MNPT x 3\/4 in. FHT PVC Swivel",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":2.56,
            "price4each":2.56,
            "totalLeft":2.56,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Orbit-1-2-in-MNPT-x-3-4-in-FHT-PVC-Swivel-53365\/202257138",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13428,
            "naming":"ONE+ 18V Cordless Wet\/Dry Hand Vacuum (Tool Only)",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":49.97,
            "price4each":49.97,
            "totalLeft":49.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/RYOBI-ONE-18V-Cordless-Wet-Dry-Hand-Vacuum-Tool-Only-PCL702B\/319962861",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13427,
            "naming":"1\/2 in. x 260 in. Thread Sealing PTFE Plumber's Tape",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":0.98,
            "price4each":0.98,
            "totalLeft":0.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Harvey-1-2-in-x-260-in-Thread-Sealing-PTFE-Plumber-s-Tape-0178503\/202280370",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13426,
            "naming":"3\/4 in. MIP Brass No-Kink Hose Bibb Valve",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":10.65,
            "price4each":10.65,
            "totalLeft":10.65,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Everbilt-3-4-in-MIP-Brass-No-Kink-Hose-Bibb-Valve-102-304EB\/205821746",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13425,
            "naming":"1\/2 in. x 3\/4 in. Brass Sweat or FTG Hose Bibb",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":6.25,
            "price4each":6.25,
            "totalLeft":6.25,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Everbilt-1-2-in-x-3-4-in-Brass-Sweat-or-FTG-Hose-Bibb-102-534EB\/205821848",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13424,
            "naming":"3\/8 in. Compression x 7\/8 in. Ballcock Nut x 12 in. Braided Polymer Toilet Supply Line",
            "type":"Shelves and racks",
            "responsible":"And Adam",
            "amount":1,
            "total":4.68,
            "price4each":4.68,
            "totalLeft":4.68,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/BrassCraft-3-8-in-Compression-x-7-8-in-Ballcock-Nut-x-12-in-Braided-Polymer-Toilet-Supply-Line-B1-12DL-F\/100094502",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13423,
            "naming":"60-Watt Equivalent A19 Dimmable CEC Title 20 ENERGY STAR 90+ CRI E26 Medium Base LED Light Bulb, Daylight 5000K (4-Pack)",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":4,
            "total":11.48,
            "price4each":2.87,
            "totalLeft":11.48,
            "amountLeft":4,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Feit-Electric-60-Watt-Equivalent-A19-Dimmable-CEC-Title-20-ENERGY-STAR-90-CRI-E26-Medium-Base-LED-Light-Bulb-Daylight-5000K-4-Pack-OM60DM-950CA-4\/304116331",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13422,
            "naming":"3\/4 in. Plastic Water Pressure Test Gauge",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":12.74,
            "price4each":12.74,
            "totalLeft":12.74,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Watts-3-4-in-Plastic-Water-Pressure-Test-Gauge-DP-IWTG\/100175467",
            "source":"The Home Depot",
            "supplyDate":"29.01.2024"
        },
        {
            "id":13407,
            "naming":"5\/8 in. Dia. x 100 ft. Heavy-Duty Commercial Grade Water Hose",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":69.98,
            "price4each":69.98,
            "totalLeft":69.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/fitt-5-8-in-Dia-x-100-ft-Heavy-Duty-Commercial-Grade-Water-Hose-FFP55800\/314440026",
            "source":"The Home Depot",
            "supplyDate":"28.01.2024"
        },
        {
            "id":13406,
            "naming":"150 ft. Hose Hangout",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":2,
            "total":13.96,
            "price4each":6.98,
            "totalLeft":13.96,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Suncast-150-ft-Hose-Hangout-CPLHH15000\/100121089",
            "source":"The Home Depot",
            "supplyDate":"28.01.2024"
        },
        {
            "id":13405,
            "naming":"Melnor  Rear-Trigger 7-Pattern Nozzle",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":6.98,
            "price4each":6.98,
            "totalLeft":6.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Melnor-Rear-Trigger-7-Pattern-Nozzle-67000HD\/314333719",
            "source":"The Home Depot",
            "supplyDate":"28.01.2024"
        },
        {
            "id":13377,
            "naming":"FOLEX CARPET SPOT REMOVER 36OZ",
            "type":"For floor",
            "responsible":"G R",
            "amount":36,
            "total":7,
            "price4each":0.19,
            "totalLeft":7,
            "amountLeft":36,
            "unit":"fl. OZ",
            "givenTotal":0,
            "source":"The Home Depot",
            "supplyDate":"11.01.2024"
        },
        {
            "id":13376,
            "naming":"ZEP PREMIUM CARPET CLEANER 128OZ",
            "type":"For floor",
            "responsible":"G R",
            "amount":128,
            "total":13,
            "price4each":0.1,
            "totalLeft":13,
            "amountLeft":128,
            "unit":"fl. OZ",
            "givenTotal":0,
            "source":"The Home Depot",
            "supplyDate":"11.01.2024"
        },
        {
            "id":13374,
            "naming":"1200gsm 600gsm microfiber auto quick drying thickened car cleaning towel 40*40",
            "type":"Consumables",
            "responsible":"G R",
            "amount":50,
            "total":30,
            "price4each":0.6,
            "totalLeft":30,
            "amountLeft":50,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/x.alibaba.com\/AvYfHO?ck=pdp",
            "source":"Alibaba",
            "supplyDate":"23.01.2024"
        },
        {
            "id":13373,
            "naming":"Custom Microfiber Cloth 30x30 Grey",
            "type":"Consumables",
            "responsible":"G R",
            "amount":150,
            "total":55.1,
            "price4each":0.37,
            "totalLeft":54.73,
            "amountLeft":149,
            "unit":"шт.",
            "givenAmount":-1,
            "givenTotal":-0.37,
            "link":"https:\/\/x.alibaba.com\/AvYfD6?ck=pdp",
            "source":"Alibaba",
            "supplyDate":"23.01.2024"
        },
        {
            "id":13372,
            "naming":"Custom Microfiber Cloth 30x30 Blu",
            "type":"Consumables",
            "responsible":"G R",
            "amount":150,
            "total":55.1,
            "price4each":0.37,
            "totalLeft":54.73,
            "amountLeft":149,
            "unit":"шт.",
            "givenAmount":-1,
            "givenTotal":-0.37,
            "link":"https:\/\/x.alibaba.com\/AvYfD6?ck=pdp",
            "source":"Alibaba",
            "supplyDate":"23.01.2024"
        },
        {
            "id":13371,
            "naming":"Custom Microfiber Cloth 30x30 Yellow",
            "type":"Consumables",
            "responsible":"G R",
            "amount":150,
            "total":55.1,
            "price4each":0.37,
            "totalLeft":54.73,
            "amountLeft":149,
            "unit":"шт.",
            "givenAmount":-1,
            "givenTotal":-0.37,
            "link":"https:\/\/x.alibaba.com\/AvYfD6?ck=pdp",
            "source":"Alibaba",
            "supplyDate":"23.01.2024"
        },
        {
            "id":13370,
            "naming":"Custom Microfiber Cloth 30x30 Green",
            "type":"Consumables",
            "responsible":"G R",
            "amount":150,
            "total":55.1,
            "price4each":0.37,
            "totalLeft":54.73,
            "amountLeft":149,
            "unit":"шт.",
            "givenAmount":-1,
            "givenTotal":-0.37,
            "link":"https:\/\/x.alibaba.com\/AvYfD6?ck=pdp",
            "source":"Alibaba",
            "supplyDate":"23.01.2024"
        },
        {
            "id":13369,
            "naming":"Custom Microfiber Cloth 30x30 Red",
            "type":"Consumables",
            "responsible":"G R",
            "amount":150,
            "total":55.1,
            "price4each":0.37,
            "totalLeft":54.73,
            "amountLeft":149,
            "unit":"шт.",
            "givenAmount":-1,
            "givenTotal":-0.37,
            "link":"https:\/\/x.alibaba.com\/AvYfD6?ck=pdp",
            "source":"Alibaba",
            "supplyDate":"23.01.2024"
        },
        {
            "id":13341,
            "naming":"Drain Weasel Hair Clog Tool Starter Kit for Drain Cleaning (3-Piece)",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":3.98,
            "price4each":3.98,
            "totalLeft":3.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/FlexiSnake-Drain-Weasel-Hair-Clog-Tool-Starter-Kit-for-Drain-Cleaning-3-Piece-DWPSK2\/203483754",
            "source":"The Home Depot",
            "supplyDate":"21.01.2024"
        },
        {
            "id":13340,
            "naming":"4-1\/2 lbs. Splitting maul 35 in. Fiberglass Handle",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":39.98,
            "price4each":39.98,
            "totalLeft":39.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-4-1-2-lbs-Splitting-maul-35-in-Fiberglass-Handle-35297\/323070140",
            "source":"The Home Depot",
            "supplyDate":"21.01.2024"
        },
        {
            "id":13267,
            "naming":"Brinks Zinc Diecast 40mm Combination Sport Padlock with 1 3\/16in Shackle",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":9.97,
            "price4each":9.97,
            "totalLeft":9.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Brinks-Zinc-Diecast-40mm-Combination-Sport-Padlock-with-1-3-16in-Shackle\/16783286?from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13266,
            "naming":"Hyper Tough 67402-26 Leather Palm Glove, Large, Multi-Use Work Glove",
            "type":"Gloves",
            "responsible":"And Adam",
            "amount":2,
            "total":4.88,
            "price4each":2.44,
            "totalLeft":4.88,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Hyper-Tough-67402-26-Leather-Palm-Glove-Large-Multi-Use-Work-Glove\/187118078?athbdg=L1102&from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13265,
            "naming":"Hyper Tough Assorted 4 inch and 8 inch Cable Ties 650Pcs",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":650,
            "total":10.17,
            "price4each":0.02,
            "totalLeft":10.17,
            "amountLeft":650,
            "unit":"шт.",
            "givenAmount":1,
            "givenTotal":0.02,
            "link":"https:\/\/www.walmart.com\/ip\/Hyper-Tough-Assorted-4-inch-and-8-inch-Cable-Ties-650Pcs\/460543628?from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13264,
            "naming":"HT 3 OL 2FT PWR STRP FABRIC",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":4.98,
            "price4each":4.98,
            "totalLeft":4.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/HT-3-OL-2FT-PWR-STRP-FABRIC\/931782089?athbdg=L1600&from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13263,
            "naming":"Hyper Tough 500-Piece Zinc Plated Steel Screw and Anchor",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":500,
            "total":11.97,
            "price4each":0.02,
            "totalLeft":11.97,
            "amountLeft":500,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Hyper-Tough-500-Piece-Zinc-Plated-Steel-Screw-and-Anchor-Fastener-Assortment-with-Case-5532\/417034609?athbdg=L1600&from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13262,
            "naming":"Mega Clamp Yellow\/black, MC 0903",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":4.63,
            "price4each":4.63,
            "totalLeft":4.63,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Mega-Clamp-Yellow-black-MC-0903\/972296565?athbdg=L1600&from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13261,
            "naming":"HART 24in Rolling Tool Box, Portable Black Resin Toolbox",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":47.88,
            "price4each":47.88,
            "totalLeft":47.88,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/HART-24in-Rolling-Tool-Box-Portable-Black-Resin-Toolbox\/735517326?athbdg=L1600&from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13260,
            "naming":"White Vertical Blinds Head Rail for Sliding Doors or Windows - 78 in. W",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":50.86,
            "price4each":50.86,
            "totalLeft":50.86,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Hampton-Bay-White-Vertical-Blinds-Head-Rail-for-Sliding-Doors-or-Windows-78-in-W-10793478808564\/300147149",
            "source":"The Home Depot",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13259,
            "naming":"Husky 6lb FG DHL SLEDGE HAMMER",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":32.45,
            "price4each":32.45,
            "totalLeft":32.45,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-6-lbs-FiberGlass-hdl-Sledge-Hammer-MD-6F-HD\/322786042",
            "source":"The Home Depot",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13258,
            "naming":"Captain Jack's 16 oz Rose Rx Ready-to-Use Spray for Insect, Fungus, Mite and Nematode Control",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":32,
            "total":5.24,
            "price4each":0.16,
            "totalLeft":5.24,
            "amountLeft":32,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Captain-Jack-s-16-oz-Rose-Rx-Ready-to-Use-Spray-for-Insect-Fungus-Mite-and-Nematode-Control\/528635768?from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13257,
            "naming":"Libman Whisk Broom with Dust Pan -Red",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":5.97,
            "price4each":5.97,
            "totalLeft":5.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.walmart.com\/ip\/Libman-Whisk-Broom-with-Dust-Pan-Red\/750854492?from=\/search",
            "source":"Walmart",
            "supplyDate":"07.01.2024"
        },
        {
            "id":13211,
            "naming":"Roman Scraper with Roller",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":1,
            "total":11.98,
            "price4each":11.98,
            "totalLeft":11.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Roman-Scraper-with-Roller-202233\/323871558",
            "source":"The Home Depot",
            "supplyDate":"27.12.2023"
        },
        {
            "id":13210,
            "naming":"HDX 33-39 Gal. Black Heavy Duty Drawstring Trash Bags",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":50,
            "total":15.97,
            "price4each":0.3,
            "totalLeft":15.97,
            "amountLeft":50,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/HDX-33-39-Gal-Black-Heavy-Duty-Drawstring-Trash-Bags-50-Count-For-Outdoor-and-Yard-Waste-HDX3339\/306713149",
            "source":"The Home Depot",
            "supplyDate":"27.12.2023"
        },
        {
            "id":13209,
            "naming":"RYOBI 6 in. Buffing Wheel Set (3-Piece)",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":19.97,
            "price4each":19.97,
            "totalLeft":19.97,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/RYOBI-6-in-Buffing-Wheel-Set-3-Piece-A92301\/319700937",
            "source":"The Home Depot",
            "supplyDate":"27.12.2023"
        },
        {
            "id":13208,
            "naming":"Goof Off 128 fl. oz. ",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":128,
            "total":25.96,
            "price4each":0.2,
            "totalLeft":25.96,
            "amountLeft":128,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Goof-Off-128-fl-oz-Professional-Strength-Latex-Paint-and-Adhesive-Remover-FG657\/100671754",
            "source":"The Home Depot",
            "supplyDate":"27.12.2023"
        },
        {
            "id":13207,
            "naming":"Fabuloso Lavender 2x Concentrated All-Purpose Cleaner",
            "type":"For floor",
            "responsible":"G R",
            "amount":128,
            "total":9.98,
            "price4each":0.08,
            "totalLeft":8.06,
            "amountLeft":104,
            "unit":"fl. OZ",
            "givenAmount":-24,
            "givenTotal":-1.92,
            "link":"https:\/\/www.homedepot.com\/p\/Fabuloso-128-oz-Fabuloso-Lavender-2x-Concentrated-All-Purpose-Cleaner-61037884\/325338360",
            "source":"The Home Depot",
            "supplyDate":"27.12.2023"
        },
        {
            "id":13206,
            "naming":"HDX 32oz. Empty Spray Bottle",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":2.68,
            "price4each":2.68,
            "totalLeft":2.68,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/HDX-32oz-Empty-Spray-Bottle-HDX32102\/320063601",
            "source":"The Home Depot",
            "supplyDate":"27.12.2023"
        },
        {
            "id":13205,
            "naming":"RYOBI 2.6 Amp Corded 5 in. Random Orbital Sander",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":69,
            "price4each":69,
            "totalLeft":69,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/RYOBI-2-6-Amp-Corded-5-in-Random-Orbital-Sander-RS290G\/205105594",
            "source":"The Home Depot",
            "supplyDate":"27.12.2023"
        },
        {
            "id":13183,
            "naming":"Husky  42 Gal. Contractor Bags (50-Count)",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":50,
            "total":29.97,
            "price4each":0.6,
            "totalLeft":29.97,
            "amountLeft":50,
            "unit":"шт.",
            "givenAmount":25,
            "givenTotal":15,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-42-Gal-Contractor-Bags-50-Count-HK42WC050B\/202973825",
            "source":"The Home Depot",
            "supplyDate":"26.12.2023"
        },
        {
            "id":13182,
            "naming":"HDX  Yellow and Blue 11 mil Reusable Latex Kitchen and Bath Gloves (2-Pair)",
            "type":"Gloves",
            "responsible":"G R",
            "amount":4,
            "total":7.96,
            "price4each":1.99,
            "totalLeft":5.97,
            "amountLeft":3,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/HDX-Yellow-and-Blue-11-mil-Reusable-Latex-Kitchen-and-Bath-Gloves-2-Pair-24125-012\/319285480",
            "source":"The Home Depot",
            "supplyDate":"26.12.2023"
        },
        {
            "id":13181,
            "naming":"BEHR DECKplus 1 gal",
            "type":"Consumables",
            "responsible":"And Adam",
            "amount":1,
            "total":36.98,
            "price4each":36.98,
            "totalLeft":36.98,
            "amountLeft":1,
            "unit":"Gal.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/BEHR-DECKplus-1-gal-Cedar-Naturaltone-Transparent-Waterproofing-Exterior-Wood-Finish-40101\/100125017",
            "source":"The Home Depot",
            "supplyDate":"26.12.2023"
        },
        {
            "id":13180,
            "naming":"4 in. Flat Chip Brush",
            "type":"Hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":4.27,
            "price4each":4.27,
            "totalLeft":4.27,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/2-in-Flat-Chip-Brush-1500-2\/100626098",
            "source":"The Home Depot",
            "supplyDate":"26.12.2023"
        },
        {
            "id":13179,
            "naming":"Anvil  47 in. L Wood Handle 14-Tines Garden Bow Rake",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":14.98,
            "price4each":14.98,
            "totalLeft":14.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.homedepot.com\/p\/Anvil-47-in-L-Wood-Handle-14-Tines-Garden-Bow-Rake-77105-943\/314816653",
            "source":"The Home Depot",
            "supplyDate":"26.12.2023"
        },
        {
            "id":13178,
            "naming":"Husky d-handle poly scoop",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":34.98,
            "price4each":34.98,
            "totalLeft":34.98,
            "amountLeft":1,
            "unit":"шт.",
            "givenAmount":1,
            "givenTotal":34.98,
            "link":"https:\/\/www.homedepot.com\/p\/Husky-31-in-Wood-Handle-D-Grip-Plastic-Scoop-Shovel-77540-945\/315067729",
            "source":"The Home Depot",
            "supplyDate":"26.12.2023"
        },
        {
            "id":13160,
            "naming":"H‑E‑B Microfiber Extendable Duster",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":1,
            "total":11,
            "price4each":11,
            "totalLeft":0,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/h-e-b-microfiber-extendable-duster-each\/2751026",
            "source":"HEB",
            "supplyDate":"13.12.2023"
        },
        {
            "id":13159,
            "naming":"Febreze Fabric Refresher Spray - Sweet Peony",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":27,
            "total":5,
            "price4each":0.19,
            "totalLeft":-0.13,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/febreze-fabric-refresher-spray-sweet-peony-27-oz\/9760508",
            "source":"HEB",
            "supplyDate":"13.12.2023"
        },
        {
            "id":13158,
            "naming":"Lysol Power Clinging Gel Toilet Bowl Cleaner Value Pack",
            "type":"For toilet",
            "responsible":"G R",
            "amount":96,
            "total":6,
            "price4each":0.06,
            "totalLeft":6,
            "amountLeft":96,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/lysol-power-clinging-gel-toilet-bowl-cleaner-value-pack-48-oz\/1358484",
            "source":"HEB",
            "supplyDate":"13.12.2023"
        },
        {
            "id":13157,
            "naming":"Fabuloso Lavender Complete Multi-Purpose Cleaner",
            "type":"For floor",
            "responsible":"G R",
            "amount":48,
            "total":5,
            "price4each":0.1,
            "totalLeft":0.2,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/fabuloso-lavender-complete-multi-purpose-cleaner-48-oz\/5650069",
            "source":"HEB",
            "supplyDate":"13.12.2023"
        },
        {
            "id":13156,
            "naming":"Premium Gloves",
            "type":"Workwear",
            "responsible":"G R",
            "amount":2,
            "total":7.25,
            "price4each":3.62,
            "totalLeft":3.63,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.heb.com\/product-detail\/h-e-b-premium-reuseable-gloves-medium\/2094578",
            "source":"HEB",
            "supplyDate":"13.12.2023"
        },
        {
            "id":13010,
            "naming":"Brasso-2660089334 Multi-Purpose Metal Polish, 8 oz",
            "type":"For metal",
            "responsible":"G R",
            "amount":1,
            "total":4.98,
            "price4each":4.98,
            "totalLeft":0,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B00D600PLA?ref_=cm_sw_r_apin_dp_S84S7EQ6W161QF7WNSJE&peakEvent=5&dealEvent=1&language=en-US",
            "source":"Amazon"
        },
        {
            "id":13009,
            "naming":"CLARK’S Natural Stone Wax",
            "type":"For ceramics",
            "responsible":"G R",
            "amount":1,
            "total":21.95,
            "price4each":21.95,
            "totalLeft":0,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B07N4ZDRRW?ref_=cm_sw_r_apin_dp_VV4WK8RFAWZJMVNEZYS1&peakEvent=5&dealEvent=1&language=en-US",
            "source":"Amazon"
        },
        {
            "id":13008,
            "naming":"APULITO Home Mold Stain Cleaning Gel Mildew Cleaner Gel for Bathroom Kitchen Household (5 Fl Oz (Pack of 3))",
            "type":"For baths",
            "responsible":"G R",
            "amount":3,
            "total":25.98,
            "price4each":8.66,
            "totalLeft":25.98,
            "amountLeft":3,
            "unit":"шт.",
            "givenAmount":1,
            "givenTotal":8.66,
            "link":"https:\/\/www.amazon.com\/dp\/B088BJXYHT?ref_=cm_sw_r_apin_dp_AN855AX6ESGW29KKQ3XA&peakEvent=5&dealEvent=1&language=en-US",
            "source":"Amazon"
        },
        {
            "id":12992,
            "naming":"Method All-Purpose Cleaner Refill",
            "type":"Multi-purpose chemistry",
            "responsible":"And Adam",
            "amount":408,
            "total":49.74,
            "price4each":0.12,
            "totalLeft":40.02,
            "amountLeft":327,
            "unit":"fl. OZ",
            "givenAmount":64,
            "givenTotal":7.68,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B07KYG8NZR\/ref=asin_title?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12991,
            "naming":"Clorox Toilet Bowl Cleaner with Bleach",
            "type":"For toilet",
            "responsible":"G R",
            "amount":8,
            "total":56.9,
            "price4each":7.11,
            "totalLeft":56.9,
            "amountLeft":8,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0B1GVFVZM?ref_=cm_sw_r_apin_dp_0T67ZHHCHVX1AGJV7YRH&language=en-US",
            "source":"Amazon"
        },
        {
            "id":12990,
            "naming":"CLR PRO Calcium, Lime and Rust Remover",
            "type":"For baths",
            "responsible":"G R",
            "amount":128,
            "total":28.03,
            "price4each":0.22,
            "totalLeft":23.63,
            "amountLeft":108,
            "unit":"fl. OZ",
            "givenAmount":60,
            "givenTotal":13.2,
            "link":"https:\/\/www.amazon.com\/dp\/B000SKX0N6?ref_=cm_sw_r_apin_dp_6GBZNWG2C21SVAFPPCBQ&language=en-US&th=1",
            "source":"Amazon"
        },
        {
            "id":12989,
            "naming":"Parkway Distributors Fabuloso Purple Lavender Scent Floor Cleaner",
            "type":"For floor",
            "responsible":"G R",
            "amount":128,
            "total":29.8,
            "price4each":0.23,
            "totalLeft":18.3,
            "amountLeft":78,
            "unit":"fl. OZ",
            "givenAmount":84,
            "givenTotal":19.32,
            "link":"https:\/\/www.amazon.com\/dp\/B0C8221VKD?ref_=cm_sw_r_apin_dp_9X73KVKBAYDCPJG3EN37&language=en-US",
            "source":"Amazon"
        },
        {
            "id":12988,
            "naming":"Bravo Low Splash Regular Bleach",
            "type":"For floor",
            "responsible":"G R",
            "amount":121,
            "total":6.67,
            "price4each":0.06,
            "totalLeft":3.01,
            "amountLeft":60,
            "unit":"fl. OZ",
            "givenAmount":40,
            "givenTotal":2.4,
            "link":"https:\/\/www.heb.com\/product-detail\/h-e-b-bravo-low-splash-regular-bleach-121-oz\/5848013",
            "source":"HEB"
        },
        {
            "id":12987,
            "naming":"Comet Scratch Free Powder Cleanser",
            "type":"For ceramics",
            "responsible":"G R",
            "amount":8,
            "total":8.96,
            "price4each":1.12,
            "totalLeft":-1.12,
            "amountLeft":-1,
            "unit":"шт.",
            "givenAmount":-2,
            "givenTotal":-2.24,
            "link":"https:\/\/www.heb.com\/product-detail\/comet-scratch-free-powder-cleanser-with-bleach-21-oz\/612095",
            "source":"HEB"
        },
        {
            "id":12986,
            "naming":"Hill Country Fare Glass Cleaner",
            "type":"For glass and windows",
            "responsible":"G R",
            "amount":406,
            "total":18.6,
            "price4each":0.05,
            "totalLeft":14.55,
            "amountLeft":325,
            "unit":"fl. OZ",
            "givenAmount":40,
            "givenTotal":2,
            "link":"https:\/\/www.heb.com\/product-detail\/hill-country-fare-glass-cleaner-with-ammonia-refill-67-6-oz\/3394003",
            "source":"HEB"
        },
        {
            "id":12985,
            "naming":"Febreze Fabric Refresher Spray",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":7,
            "total":39.9,
            "price4each":5.7,
            "totalLeft":39.9,
            "amountLeft":7,
            "unit":"шт.",
            "givenAmount":3,
            "givenTotal":17.1,
            "link":"https:\/\/www.heb.com\/product-detail\/febreze-fabric-refresher-spray-sweet-peony-27-oz\/9760508",
            "source":"HEB"
        },
        {
            "id":12980,
            "naming":"Black Diamond Stoneworks MARBLE & TILE FLOOR CLEANER",
            "type":"For floor",
            "responsible":"G R",
            "amount":128,
            "total":34.98,
            "price4each":0.27,
            "totalLeft":18.51,
            "amountLeft":67,
            "unit":"fl. OZ",
            "givenAmount":40,
            "givenTotal":10.8,
            "link":"https:\/\/www.amazon.com\/dp\/B00J75IU6A?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12975,
            "naming":"CleanSmart Toy Disinfectant Spray",
            "type":"ECO",
            "responsible":"G R",
            "amount":2,
            "total":15.28,
            "price4each":7.64,
            "totalLeft":15.28,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B011ANDC78\/ref=asin_title?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12974,
            "naming":"ANECO Compostable Trash Bags",
            "type":"Consumables",
            "responsible":"G R",
            "amount":100,
            "total":17.6,
            "price4each":0.18,
            "totalLeft":17.6,
            "amountLeft":100,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B095CGWKWW\/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12961,
            "naming":"75 Inch Wall Mop Wall Cleaning Mop",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":2,
            "total":18.99,
            "price4each":9.49,
            "totalLeft":18.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenAmount":1,
            "givenTotal":9.49,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B09K3FHSSZ\/ref=ppx_yo_dt_b_asin_title_o00_s03?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12960,
            "naming":"Easy-Off Professional Oven & Grill Cleaner",
            "type":"For metal",
            "responsible":"G R",
            "amount":6,
            "total":44.98,
            "price4each":7.5,
            "totalLeft":37.48,
            "amountLeft":5,
            "unit":"шт.",
            "givenAmount":3,
            "givenTotal":22.5,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B0040ZORB4\/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12958,
            "naming":"2Pack Pumice Stone Toilet Bowl Cleaning",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":2,
            "total":6.99,
            "price4each":3.5,
            "totalLeft":6.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B0B7WZQ6ZJ\/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12956,
            "naming":"BETTER LIFE Bathroom Cleaner - Tea Tree Bathtub & Shower Cleaner",
            "type":"ECO",
            "responsible":"G R",
            "amount":64,
            "total":22.99,
            "price4each":0.36,
            "totalLeft":22.99,
            "amountLeft":64,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B07L4H21T6\/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12955,
            "naming":"Lysol Bleach Free Hydrogen Peroxide Toilet Bowl Cleaner",
            "type":"For toilet",
            "responsible":"G R",
            "amount":144,
            "total":28.89,
            "price4each":0.2,
            "totalLeft":14.49,
            "amountLeft":72,
            "unit":"fl. OZ",
            "givenAmount":24,
            "givenTotal":4.8,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B0B9HYG6V8\/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12953,
            "naming":"16.5FT Telescoping Ladder",
            "type":"Outdoor hand tools",
            "responsible":"And Adam",
            "amount":1,
            "total":329.99,
            "price4each":329.99,
            "totalLeft":329.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0CBPTY82H?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12952,
            "naming":"Ecover Toilet Bowl Cleaner",
            "type":"ECO",
            "responsible":"G R",
            "amount":25,
            "total":7,
            "price4each":0.28,
            "totalLeft":7,
            "amountLeft":25,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B004T33D3A\/ref=ppx_yo_dt_b_asin_title_o03_s02?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12949,
            "naming":"Harper Live.Love.Clean. Household Cleaning Kit",
            "type":"ECO",
            "responsible":"G R",
            "amount":2,
            "total":67.81,
            "price4each":33.91,
            "totalLeft":67.81,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B09HJFWT5M\/ref=ppx_yo_dt_b_asin_title_o03_s01?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12948,
            "naming":"HALOMOUNT Monitor Laptop Mount",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":44.29,
            "price4each":44.29,
            "totalLeft":44.29,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0C9GPF434?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12947,
            "naming":"NPET K32 Wireless Gaming Keyboard",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":24.99,
            "price4each":24.99,
            "totalLeft":24.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B07GBSGTKV?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12946,
            "naming":"Monitoracer EK240Y C - 23.8\" Monitor",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":100,
            "price4each":100,
            "totalLeft":100,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0BNHXRXLN?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12945,
            "naming":"EZPRO USA Plastic Spray Bottle 24 Oz",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":3,
            "total":11,
            "price4each":3.67,
            "totalLeft":11,
            "amountLeft":3,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B08GZX1J27?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12944,
            "naming":"MOUYAT 23 Inch Large Pick Mattock Hoe",
            "type":"Outdoor hand tools",
            "responsible":"G R",
            "amount":1,
            "total":27.99,
            "price4each":27.99,
            "totalLeft":27.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B09YXTYPSJ?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12943,
            "naming":"HANTOP Garden Shovel",
            "type":"Outdoor hand tools",
            "responsible":"G R",
            "amount":1,
            "total":28.99,
            "price4each":28.99,
            "totalLeft":28.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0C3VDDB5F?ref=ppx_yo2ov_dt_b_product_details&th=1",
            "source":"Amazon"
        },
        {
            "id":12942,
            "naming":"WD-40 Original Forumla",
            "type":"Multi-purpose chemistry",
            "responsible":"G R",
            "amount":3,
            "total":18.83,
            "price4each":6.28,
            "totalLeft":18.83,
            "amountLeft":3,
            "unit":"шт.",
            "givenAmount":3,
            "givenTotal":18.84,
            "link":"https:\/\/www.amazon.com\/dp\/B084CQ4R8L?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12939,
            "naming":"Eaasty 12 Pack Plastic Spray Bottles 25 oz",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":12,
            "total":41.99,
            "price4each":3.5,
            "totalLeft":41.99,
            "amountLeft":12,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0CGV5TW6W?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12938,
            "naming":"30 Inch Pre Streched Braiding Hair 3 Packs Synthetic Colored Braiding Hair",
            "type":"For hair",
            "responsible":"G R",
            "amount":3,
            "total":13.66,
            "price4each":4.55,
            "totalLeft":13.66,
            "amountLeft":3,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0C6M7T95Y?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12937,
            "naming":"Mytium Window Cleaning Squeegee Kit",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":1,
            "total":17.99,
            "price4each":17.99,
            "totalLeft":17.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0BNB5NY87?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12936,
            "naming":"2 Pcs Shower Squeegee for Shower Glass Doors",
            "type":"Consumables",
            "responsible":"G R",
            "amount":2,
            "total":6.99,
            "price4each":3.5,
            "totalLeft":6.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0BXB88KY6?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12935,
            "naming":"NIIMBOT Label Maker Tape",
            "type":"Electrical equipment",
            "responsible":"G R",
            "amount":1,
            "total":11.99,
            "price4each":11.99,
            "totalLeft":11.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B09D744PTJ?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12934,
            "naming":"PrinterNIIMBOT B21 Inkless Label Maker",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":1,
            "total":65.99,
            "price4each":65.99,
            "totalLeft":65.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B09C1VWT2N?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12933,
            "naming":"HTVRONT Vinyl Scraper",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":2,
            "total":5.99,
            "price4each":3,
            "totalLeft":5.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B095VRHHP6?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12932,
            "naming":"100 Pack Heavy Duty Cleaning Scrub Sponges for Kitchen Abrasive Scrubber Sponge",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":100,
            "total":28.99,
            "price4each":0.29,
            "totalLeft":28.99,
            "amountLeft":100,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0BNBZPMPT?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12931,
            "naming":"Housmile Mesh File Folder Organizer",
            "type":"Shelves and racks",
            "responsible":"And Adam",
            "amount":2,
            "total":35.99,
            "price4each":18,
            "totalLeft":35.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0C9C2Q13B?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12930,
            "naming":"Baseboard Buddy – Baseboard & Molding Cleaning Tool",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":2,
            "total":24.99,
            "price4each":12.49,
            "totalLeft":24.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenAmount":2,
            "givenTotal":24.98,
            "link":"https:\/\/www.amazon.com\/dp\/B01C6X37Q2?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12929,
            "naming":"MR.SIGA Microfiber Cleaning Cloth",
            "type":"Consumables",
            "responsible":"G R",
            "amount":50,
            "total":24.99,
            "price4each":0.5,
            "totalLeft":24.99,
            "amountLeft":50,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B07XT288Y5?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12928,
            "naming":"MR.SIGA Ultra Fine Microfiber Cloths for Glass",
            "type":"Consumables",
            "responsible":"G R",
            "amount":12,
            "total":19.99,
            "price4each":1.67,
            "totalLeft":19.99,
            "amountLeft":12,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B071JLQ387?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12926,
            "naming":"Simple Deluxe Heavy Duty 5-Shelf Shelving Unit 1250Lb Capacity",
            "type":"Shelves and racks",
            "responsible":"And Adam",
            "amount":5,
            "total":312,
            "price4each":62.4,
            "totalLeft":312,
            "amountLeft":5,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0BCP5MM6K?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12925,
            "naming":"Reli. SuperValue 33 Gallon Trash Bags",
            "type":"Consumables",
            "responsible":"G R",
            "amount":50,
            "total":13.99,
            "price4each":0.28,
            "totalLeft":13.99,
            "amountLeft":50,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0B7Q8BPZL?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12924,
            "naming":"Electric Car Jack Kit 5Ton 12V Hydraulic Car Jack Lift",
            "type":"Car tools",
            "responsible":"And Adam",
            "amount":1,
            "total":102.99,
            "price4each":102.99,
            "totalLeft":102.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0CHYMDBCS?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12923,
            "naming":"3 Inch Car Headlight Restoration Kit",
            "type":"Car tools",
            "responsible":"And Adam",
            "amount":3,
            "total":16.99,
            "price4each":5.66,
            "totalLeft":16.99,
            "amountLeft":3,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B09B3BKHF1?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12922,
            "naming":"Meguiar's PlastX Clear Plastic Polish",
            "type":"Car tools",
            "responsible":"And Adam",
            "amount":10,
            "total":7.64,
            "price4each":0.76,
            "totalLeft":7.64,
            "amountLeft":10,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0000AY3SR?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12921,
            "naming":"Gonhom Par38 LED Flood Light Bulbs Outdoor 2 Pack",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":2,
            "total":16.99,
            "price4each":8.49,
            "totalLeft":16.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B09WZRR67F?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12920,
            "naming":"Trowbridge's Grafting Wax 8 oz. WALTER E. CLARK & SON",
            "type":"For trees",
            "responsible":"And Adam",
            "amount":8,
            "total":4.24,
            "price4each":0.53,
            "totalLeft":4.24,
            "amountLeft":8,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B000NCTJCU?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12919,
            "naming":"KURUI Heavy Duty Hollow Wall Anchors for Drywall",
            "type":"For walls",
            "responsible":"And Adam",
            "amount":1,
            "total":9.99,
            "price4each":9.99,
            "totalLeft":9.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"\thttps:\/\/www.amazon.com\/dp\/B09V32CKNJ?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12918,
            "naming":"LED Light Bulbs, 100 Watt Equivalent A19",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":4,
            "total":9.99,
            "price4each":2.5,
            "totalLeft":9.99,
            "amountLeft":4,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B09YQ4197R?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12917,
            "naming":"Campfun 899PCS Tool Set, Household Tool Kit with Rolling Tool Bo",
            "type":"Car tools",
            "responsible":"And Adam",
            "amount":1,
            "total":89.99,
            "price4each":89.99,
            "totalLeft":89.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0C5RY13FZ?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12916,
            "naming":"MZK 20V Pole Pruning Shear",
            "type":"For trees",
            "responsible":"And Adam",
            "amount":1,
            "total":129.99,
            "price4each":129.99,
            "totalLeft":129.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B0C2CK7Y3T?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12915,
            "naming":"PowerSmart 40V MAX Cordless Leaf Blower with 4.0Ah Battery and Charger",
            "type":"Electrical equipment",
            "responsible":"And Adam",
            "amount":2,
            "total":119.98,
            "price4each":59.99,
            "totalLeft":119.98,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/dp\/B09YPW6K8K?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        },
        {
            "id":12914,
            "naming":"PowerSmart 40V MAX 17-Inch Cordless Lawn Mower & Leaf Blower Combo Kit",
            "type":"For the lawn",
            "responsible":"And Adam",
            "amount":1,
            "total":329.99,
            "price4each":329.99,
            "totalLeft":329.99,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B0BJTYWZ9Q\/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12913,
            "naming":"Maryton Pumice Stone for Toilet Cleaning",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":16,
            "total":16.99,
            "price4each":1.06,
            "totalLeft":16.99,
            "amountLeft":16,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B07XDDQGLP\/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12912,
            "naming":"naturally It's clean Floor Cleaner (Makes 24-Gallons) for All Floor Types (Plant Based Enzymes) pH Neutral",
            "type":"ECO",
            "responsible":"G R",
            "amount":24,
            "total":9.99,
            "price4each":0.42,
            "totalLeft":9.99,
            "amountLeft":24,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B007P5YZ36\/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12911,
            "naming":"Rubber Broom for Pet Hair Carpet Rake with Squeegee",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":1,
            "total":13.59,
            "price4each":13.59,
            "totalLeft":13.59,
            "amountLeft":1,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B0BWN3S52D\/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12910,
            "naming":"Aunt Fannie's Glass & Window Cleaning Vinegar Wash",
            "type":"ECO",
            "responsible":"G R",
            "amount":3,
            "total":22.99,
            "price4each":7.66,
            "totalLeft":22.99,
            "amountLeft":3,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B08YP7CM52\/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12909,
            "naming":"Multi-Purpose Antibacterial Spray",
            "type":"ECO",
            "responsible":"G R",
            "amount":2,
            "total":11.99,
            "price4each":6,
            "totalLeft":11.99,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B0CBVZW81W\/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12908,
            "naming":"Therapy Stove Top Cleaner and Cooktop Cleaner Kit - Glass Stove Top Cleaner and Polish for Ceramic, Electric, Induction and Flat Top Surfaces",
            "type":"ECO",
            "responsible":"G R",
            "amount":32,
            "total":19.95,
            "price4each":0.62,
            "totalLeft":19.95,
            "amountLeft":32,
            "unit":"fl. OZ",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B098G5M4ZS\/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12907,
            "naming":"Baseboard Cleaner Tool with Long Handle",
            "type":"Hand tools",
            "responsible":"G R",
            "amount":2,
            "total":22.48,
            "price4each":11.24,
            "totalLeft":22.48,
            "amountLeft":2,
            "unit":"шт.",
            "givenTotal":0,
            "link":"https:\/\/www.amazon.com\/gp\/product\/B0C7Q2XXMN\/ref=ppx_yo_dt_b_asin_title_o00_s02?ie=UTF8&psc=1",
            "source":"Amazon"
        },
        {
            "id":12906,
            "naming":"Zep Foaming Wall Cleaner",
            "type":"For walls",
            "responsible":"G R",
            "amount":6,
            "total":20.21,
            "price4each":3.37,
            "totalLeft":16.84,
            "amountLeft":5,
            "unit":"шт.",
            "givenAmount":2,
            "givenTotal":6.74,
            "link":"https:\/\/www.amazon.com\/dp\/B07DX79815?psc=1&ref=ppx_yo2ov_dt_b_product_details",
            "source":"Amazon"
        }
    ]
    equipTable = new Tabulator("#equip-table",{
        data: tableData,
        maxHeight: "80%",
        addRowPos: "top",
        pagination: "local",
        paginationSize: 10,
        paginationSizeSelector: [10,20,30,50,100,true],
        paginationCounter: "rows",
        layout:"fitDataTable",
        columns:[
            {title:"Id", field:"id"},
            {title:"Наименование", field:"naming",width:"10%",editor:true},
            {title:"Тип", field:"type",editor:"list",editorParams:{
                    valuesLookup:"active",autocomplete:true,freetext:true
                }},
            {title:"Ответственный", field:"responsible",editor:"list",editorParams:{
                    valuesLookup:"active",autocomplete:true,freetext:true
                }},
            {title:"Кол-во", field:"amount",editor:"number"},
            {title:"Итого", field:"total", bottomCalc:"sum",bottomCalcParams:{precision: 1}},
            {title:"Цена за 1", field:"price4each"},
            {title:"Остаток суммы", field:"totalLeft"},
            {title:"Остаток кол-во", field:"amountLeft"},
            {title:"Ед.изм", field:"unit", editor: "list", editorParams:{
                    valuesLookup:"active", autocomplete:true, freetext:true}},
            {title:"Выдано кол-во", field:"givenAmount"},
            {title:"Выдано сумма", field:"givenTotal",bottomCalc:"sum",bottomCalcParams:{precision:1}},
            {title:"Ссылка", field:"link",width:"10%",editor: true},
            {title:"Поставщик", field:"source",editor: "list", editorParams:{
                    valuesLookup:"active", autocomplete:true, freetext:true}},
            {title:"Дата поставки", field:"supplyDate",editor: "date"},
        ]
    });

    let typeMenu = [
        {
        label:"<i class='fas fa-user'></i>Удалить ряд",
        action:function (e,row){
            row.delete();
        }
        },
    ];

    typeTable = new Tabulator("#type-table",{
        data: [{"type":"химия"},{"type":"иное"}],
        layout:"fitDataStretch",
        maxHeight: "80%",
        addRowPos: "top",
        rowContextMenu: typeMenu,
        columns: [
            {formatter:"rowSelection", titleFormatter:"rowSelection", hozAlign:"center", headerSort:false,
                cellClick:function(e, cell){
                    cell.getRow().toggleSelect();
                }},
            {title:"Тип",field:"type",editor:true}
        ]
    })

}